### ISSUE TITLE
IntIdMissingError on saving a new mirror object

### ISSUE THREAD

**Issue by pbauer** [collective/collective.mirror#1]
from https://community.plone.org/t/solved-how-to-create-aliases-ex-for-folders/12780/14: 

I get this error when saving a new mirror object:
`zope.intid.interfaces.IntIdMissingError: <Folder at /dev/en/news>`
("/dev/en/news" is the Master Container)

**Comment by tlotze** [comment]
I could only reproduce this error by unregistering the target folder's IntId. As far as I know, a content object without an IntId is not something that might be expected normally, though. So either there is something wrong with the reporter's site and IntId registration needs to be fixed there, or more precise information about how this error was produced is needed.
